springdoc:
  swagger-ui:
    path: "/swagger"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    lease-renewal-interval-in-seconds: 10  # Gateway gửi heartbeat mỗi 10 giây
    lease-expiration-duration-in-seconds: 30 # Nếu sau 30 giây không có heartbeat, Eureka sẽ xóa service
    prefer-ip-address: true
logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.cloud: TRACE


  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always