spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/authendb"
    username: root
    password: root
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 5125
  address: 0.0.0.0
jwt:
  signedJWT: "aGUDzL2OOlvQcHJE5fpfzxv0w6MUZtFhF4IRZo+Tc/z5FnKjn8xxJvoot4OVj6LP"
  valid-duration: 3600
  refreshable-duration: 360000
cors:
  allowed:
    origins:
      - "http://localhost:5173"
      - "http://26.144.191.229:5173"

