spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/imageservice?createDatabaseIfNotExists=true"
    username: root
    password: root
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 9085
  address: 0.0.0.0
springdoc:
  swagger-ui:
    path: "/swagger"
