server:
  port: 9081
  servlet:
    context-path: /
spring:
  cloud:
    gateway:
      routes:
        - id: report-routes
          uri: lb://StatisticService
          predicates:
            - Path=/statistic/**
          filters:
            - StripPrefix=1
        - id: schedule-routes
          uri: lb://ScheduleService
          predicates:
            - Path=/schedule/**
          filters:
            - StripPrefix=1
        - id: Auth_routes
          uri: http://localhost:5125
          predicates:
            - Path=/authen/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          enabled: true