spring:
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: notificationGroup
      auto-offset-reset: latest  # Đọc từ tin nhắn mới nhất (nếu cần tin cũ thì giữ 'earliest')
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  mail:
    host: smtp.gmail.com
    port: 587
    username: minhdaimk111@gmail.com
    password: qalwnukbtdganhgg
    properties:
      mail.smtp.starttls.enable: true  # ? B?t bu?c kích ho?t TLS
      mail.smtp.auth: true
      mail.smtp.ssl.trust: smtp.gmail.com
    test-connection: false
server:
  port: 9083
  address: 0.0.0.0
springdoc:
  swagger-ui:
    path: "/swagger"


