spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB
  kafka:
    bootstrap-servers: localhost:9193
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: -1
      retries: 1
  datasource:
    url: jdbc:mysql://localhost:3306/sheduledb
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          default:
            connect-timeout: 15000
            read-timeout: 15000
resilience4j:
  timelimiter:
    configs:
      default:
        timeout-duration: 15000  # Đặt thời gian tối đa cho yêu cầu là 15 giây
        cancelRunningFuture: true
  circuitbreaker:
    instances:
      NotificationService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
springdoc:
  swagger-ui:
    path: "/swagger"
server:
  port: 8081
  address: 0.0.0.0
  email:
    from: "minhdaimk111@gmail.com"

