spring:
  application:
    name: ScheduleService

  config:

    import: configserver:http://localhost:8888
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
    config:
      fail-fast: true
logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.cloud: TRACE
