spring:
  application:
    name: ScheduleService

  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: true
logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.cloud: TRACE
