spring:
  application:
    name: ServiceTEACSCHEDULE_AND_MAKE-UP_SCHEDULE_SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/webshedule
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
server:
  port: 8080
  address: 0.0.0.0

