spring:
  application:
    name: GateService
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      gateway:
        globalcors:
          corsConfigurations:
            '[/**]':
              allowedOrigins: "http://localhost:5173"
              allowedMethods: "*"
              allowedHeaders: "*"
              allowCredentials: true
      fail-fast: true
